#!/usr/bin/env python3
"""Build the archive that the paper's availability statement points to (referee checklist A12).

The archive is a zip of the repository's tracked and new, non-ignored files (``git ls-files --cached --others
--exclude-standard``), less the files listed in ``EXCLUDE`` (internal notes, colleagues' drafts, binary office files),
plus

* ``ARCHIVE_MANIFEST.txt``: the commit, the date, the Python and package versions, and the commands that regenerate
  every table and figure from the stored runs;
* ``SHA256SUMS.txt``: the checksum of every file in the archive.

It refuses to write an archive in which a text file contains a cluster account or allocation name (``FORBIDDEN``), a
user's home directory, or a path to a scratch directory of this machine.  Large derived files are not archived (they are
ignored by git and regenerated by the documented commands): cached problems, fragment standard deviations, design matrices.

    python scripts/make_archive.py [--out ../dist/paper_a_artifact.zip] [--dry-run]
"""
from __future__ import annotations

import argparse
import hashlib
import platform
import re
import subprocess
import sys
import zipfile
from datetime import date
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
EXCLUDE = (
    "reports/draft_with_colleague_notes.tex", "reports/notes_resolution.md", "reports/consistency_audit.md",
    "reports/reference_review.md", "reports/paper_edit_commands.docx", "reports/part1_fixed_gradient_measurement_report_original.tex",
    "COMMIT_MESSAGE.txt",
)
EXCLUDE_PREFIX = ("All in one/", "Claude outputs/", "reports/_superseded/", "dist/")
FORBIDDEN = [re.compile(p) for p in (r"zephrous", r"rrg-izmaylov", r"/scratch/[a-z]+/", r"C:\\Users\\", r"/home/[a-z]+/", r"/root/venvs")]
TEXT_SUFFIX = {".py", ".md", ".txt", ".tex", ".bib", ".sh", ".json", ".csv", ".cfg", ".toml", ".yml", ".yaml", ".sbatch", ""}
REGENERATE = """\
Regenerate the tables and figures from the stored runs (no cluster access needed):
  cd part2_estimator_design
  python scripts/paper_a_sota_tables.py           # runs/paper_a/sota_fixed_state.csv, sota_trajectories.csv
  python scripts/paper_a_depth_tables.py --cases H4_square_eq_side1p0_CISD H4_square_stretch_side2p0_CISD LiH_R3p0_HF LiH_R3p0_ADAPT3 LiH_R3p0_ADAPT5 H2O_eq_CISD H2O_stretch_CISD H2O_eq_ADAPT11 H2O_stretch_ADAPT8
  python scripts/paper_a_sota_latex.py --splice ../reports/draft.tex ; python scripts/paper_a_q8_text.py --paper ../reports/draft.tex
  python scripts/paper_a_discussion_tables.py --splice ../reports/draft.tex
  python scripts/paper_a_bootstrap.py --latex ../reports/generated/tab_headline_bootstrap.tex
  python scripts/paper_a_fixed_budget.py --latex ../reports/generated/tab_fixed_budget.tex
  python scripts/paper_a_figures.py
  python scripts/sanity_checks.py <cases>          # the invariants every stored result must satisfy
Rerun the simulations: scripts/step4_learned_designs.py, step5_external_baselines.py, phase4_adapt_selection.py (see their headers;
whole-node cluster jobs were used for the larger cases, 24 h each, with checkpointed trials).  Tests: python -m pytest tests -q
"""


def tracked_files() -> list[str]:
    out = subprocess.run(["git", "ls-files", "--cached", "--others", "--exclude-standard", "-z"], cwd=REPO, check=True,
                         capture_output=True).stdout.decode("utf-8", "surrogateescape")
    files = [f for f in out.split("\0") if f]
    return sorted(f for f in files if f not in EXCLUDE and not f.startswith(EXCLUDE_PREFIX) and (REPO / f).is_file())


def check_text(files: list[str]) -> list[str]:
    problems = []
    for name in files:
        path = REPO / name
        if name.endswith("scripts/make_archive.py"):
            continue  # lists the forbidden strings
        if path.suffix.lower() not in TEXT_SUFFIX or path.stat().st_size > 20_000_000:
            continue
        try:
            text = path.read_text(encoding="utf-8")
        except UnicodeDecodeError:
            continue
        for pattern in FORBIDDEN:
            hit = pattern.search(text)
            if hit:
                line = text.count("\n", 0, hit.start()) + 1
                problems.append(f"{name}:{line}: {hit.group(0)!r}")
    return problems


def versions() -> str:
    lines = [f"python {platform.python_version()} on {platform.system()}"]
    req = REPO / "part2_estimator_design" / "requirements.txt"
    if req.exists():
        lines.append("requirements.txt (part 2):")
        lines += [f"  {line}" for line in req.read_text().splitlines() if line.strip() and not line.startswith("#")]
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", type=Path, default=REPO / "dist" / "paper_a_artifact.zip")
    parser.add_argument("--dry-run", action="store_true")
    parser.add_argument("--allow-forbidden", action="store_true", help="write the archive even if a forbidden string is found")
    args = parser.parse_args()
    files = tracked_files()
    size = sum((REPO / f).stat().st_size for f in files)
    print(f"{len(files)} files, {size / 1e6:.1f} MB before compression")
    problems = check_text(files)
    for p in problems:
        print("FORBIDDEN:", p)
    if problems and not args.allow_forbidden:
        sys.exit(f"{len(problems)} forbidden strings; fix them or the file lists")
    if args.dry_run:
        return
    commit = subprocess.run(["git", "rev-parse", "HEAD"], cwd=REPO, capture_output=True, text=True).stdout.strip()
    dirty = bool(subprocess.run(["git", "status", "--porcelain"], cwd=REPO, capture_output=True, text=True).stdout.strip())
    manifest = (f"Paper A artifact, built {date.today().isoformat()} from commit {commit}{' (working tree has uncommitted changes)' if dirty else ''}\n\n"
                f"{versions()}\n\n{REGENERATE}")
    sums = []
    args.out.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(args.out, "w", zipfile.ZIP_DEFLATED, compresslevel=9) as archive:
        for name in files:
            data = (REPO / name).read_bytes()
            sums.append(f"{hashlib.sha256(data).hexdigest()}  {name}")
            archive.writestr(zipfile.ZipInfo.from_file(REPO / name, name), data, zipfile.ZIP_DEFLATED)
        archive.writestr("ARCHIVE_MANIFEST.txt", manifest)
        archive.writestr("SHA256SUMS.txt", "\n".join(sums) + "\n")
    print(f"wrote {args.out} ({args.out.stat().st_size / 1e6:.1f} MB, {len(files) + 2} entries)")


if __name__ == "__main__":
    main()
