#!/usr/bin/env python3
"""Step 2: overlap census -- the go/no-go diagnostic for coefficient splitting.

Coefficient splitting (II-A) and zero-sum auxiliaries (II-B) need Pauli products
that more than one context measures.  Part I's parent grouping is a partition, so
any overlap comes from the groups the measurement circuits actually read out,
which depend on how each context's generators are completed.  For every case and
every completion rule this script records:

* the multiplicity of every Pauli of ``B_0`` (how many contexts measure it);
* the share of each gradient's coefficient mass on Paulis of multiplicity >= 2,
  for the whole pool, the winner, the runner-up and the *binding* generator (the
  one whose reconstruction variance ``sum_alpha sigma_ialpha**2`` sets M1's cost,
  Part I Table "binding"), and for the zero- and non-zero-gradient pools;
* the number of zero-sum auxiliary candidates per generator (library Paulis
  outside ``supp(C_i)`` measured by at least two contexts that carry ``C_i``);
* the measurement-circuit cost (CZ count per context).

The ``span`` rule measures only the group generated by the parent members and is
a diagnostic lower bound, not a circuit.

Example::

    python scripts/step2_overlap_census.py --cases H4_square_eq_side1p0_HF LiH_R3p0_HF
"""
from __future__ import annotations

import argparse
import sys
import time
from pathlib import Path

import numpy as np

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))

from contexts import STRATEGIES, build_context_library, span_multiplicity  # noqa: E402
from outputs import run_record, write_csv, write_json  # noqa: E402
from part1_bridge import CASES, gradient_matrix, load_problem  # noqa: E402

MULTIPLICITY_BINS = ((1, 1), (2, 2), (3, 3), (4, 7), (8, 15), (16, 10 ** 9))
NONZERO_THRESHOLD = 1e-6


def splittable_share(A_abs, A_sq, splittable: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    """Per-generator share of |A| and of A**2 on splittable Paulis."""
    mask = splittable.astype(float)
    share = (A_abs @ mask) / np.maximum(np.asarray(A_abs.sum(axis=1)).ravel(), 1e-300)
    share_sq = (A_sq @ mask) / np.maximum(np.asarray(A_sq.sum(axis=1)).ravel(), 1e-300)
    return np.asarray(share).ravel(), np.asarray(share_sq).ravel()


def auxiliary_candidates(problem, library) -> np.ndarray:
    """Zero-sum auxiliary candidates per generator (II-B, rule (i))."""
    index = {label: position for position, label in enumerate(library.labels)}
    owners = library.contexts_of()
    counts = np.zeros(problem.n_generators, dtype=np.int64)
    for i, terms in enumerate(problem.commutator_terms):
        support = np.array([index[label] for label in terms], dtype=np.int64)
        carrying = np.unique(np.concatenate([owners[l] for l in support]))
        measured = np.concatenate([library.contexts[a].members for a in carrying])
        hits = np.bincount(measured, minlength=library.n_library)
        hits[support] = 0
        counts[i] = int((hits >= 2).sum())
    return counts


def census_row(case, strategy, problem, multiplicity, A_abs, A_sq, special, seconds, library=None):
    splittable = multiplicity >= 2
    share, share_sq = splittable_share(A_abs, A_sq, splittable)
    nonzero = problem.abs_gradients > NONZERO_THRESHOLD
    total_abs = np.asarray(A_abs.sum(axis=1)).ravel()
    row = {
        "case_id": case,
        "strategy": strategy,
        "n_required_paulis": int(multiplicity.size),
        "multiplicity_mean": float(multiplicity.mean()),
        "multiplicity_max": int(multiplicity.max()),
        "fraction_splittable": float(splittable.mean()),
        "pool_mass_share": float((share * total_abs).sum() / total_abs.sum()),
        "nonzero_pool_mass_share": float((share * total_abs)[nonzero].sum() / total_abs[nonzero].sum()),
        "zero_pool_mass_share": float((share * total_abs)[~nonzero].sum() / max(total_abs[~nonzero].sum(), 1e-300)),
        "seconds": round(seconds, 2),
    }
    for name, i in special.items():
        row[f"{name}_mass_share"] = float(share[i])
        row[f"{name}_sq_mass_share"] = float(share_sq[i])
    for lo, hi in MULTIPLICITY_BINS:
        label = f"mult_{lo}" if lo == hi else (f"mult_{lo}_{hi}" if hi < 10 ** 9 else f"mult_{lo}_plus")
        row[label] = int(((multiplicity >= lo) & (multiplicity <= hi)).sum())
    if library is not None:
        cz = library.two_qubit_counts()
        members = np.array([c.members.size for c in library.contexts])
        ranks = np.array([c.parent_rank for c in library.contexts])
        row.update(
            {
                "contexts_already_maximal": float((ranks == library.n_qubits).mean()),
                "mean_generators_from_library": float(
                    np.mean([c.completed_from_library for c in library.contexts])
                ),
                "members_per_context_mean": float(members.mean()),
                "members_per_context_max": int(members.max()),
                "cz_per_context_mean": float(cz.mean()),
                "cz_per_context_max": int(cz.max()),
            }
        )
    return row, share


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--cases", nargs="+", default=list(CASES))
    parser.add_argument("--strategies", nargs="+", default=["span", *STRATEGIES])
    parser.add_argument("--out", type=Path, default=Path("runs"))
    parser.add_argument("--no-aux", action="store_true", help="skip the II-B candidate count")
    args = parser.parse_args()

    all_rows = []
    for case in args.cases:
        problem = load_problem(case)
        A = gradient_matrix(problem)
        A_abs, A_sq = abs(A), A.multiply(A)
        sigmas = problem.parent_fragment_sigmas()
        order = problem.ranking()
        special = {
            "winner": order[0],
            "runner_up": order[1],
            "binding": int(np.argmax((sigmas ** 2).sum(axis=1))),
        }
        rows, generator_rows = [], []
        for strategy in args.strategies:
            started = time.perf_counter()
            if strategy == "span":
                multiplicity = span_multiplicity(problem)
                library = None
            else:
                library = build_context_library(problem, strategy)
                multiplicity = library.multiplicity()[: library.n_required]
            row, share = census_row(
                case, strategy, problem, multiplicity, A_abs, A_sq, special,
                time.perf_counter() - started, library,
            )
            if library is not None and not args.no_aux:
                aux = auxiliary_candidates(problem, library)
                row["aux_candidates_mean"] = float(aux.mean())
                row["aux_candidates_max"] = int(aux.max())
            else:
                aux = np.full(problem.n_generators, -1)
            rows.append(row)
            for i in range(problem.n_generators):
                generator_rows.append(
                    {
                        "strategy": strategy,
                        "generator_index": i,
                        "label": problem.labels[i],
                        "abs_gradient": float(problem.abs_gradients[i]),
                        "support_size": len(problem.commutator_terms[i]),
                        "reconstruction_variance_II0": float((sigmas[i] ** 2).sum()),
                        "splittable_mass_share": float(share[i]),
                        "aux_candidates": int(aux[i]),
                    }
                )
            print(
                f"{case:32s} {strategy:9s} mult {row['multiplicity_mean']:5.2f} "
                f"splittable {row['fraction_splittable']:6.1%}  mass: pool {row['pool_mass_share']:6.1%} "
                f"winner {row['winner_mass_share']:6.1%} binding {row['binding_mass_share']:6.1%}"
                + (f"  CZ/ctx {row['cz_per_context_mean']:5.1f}" if library is not None else "")
                + f"  ({row['seconds']:.0f}s)",
                flush=True,
            )
        directory = args.out / case
        columns = list(dict.fromkeys(key for row in rows for key in row))
        write_csv(directory / f"{case}_overlap_census.csv", columns, rows)
        write_csv(directory / f"{case}_overlap_by_generator.csv", list(generator_rows[0]), generator_rows)
        write_json(
            directory / f"{case}_overlap_census_meta.json",
            {"special_generators": {k: problem.labels[v] for k, v in special.items()}, "run": run_record()},
        )
        all_rows.extend(rows)
    columns = list(dict.fromkeys(key for row in all_rows for key in row))
    write_csv(args.out / "step2_overlap_census.csv", columns, all_rows)


if __name__ == "__main__":
    main()
