"""The Part II context library: Part I's parent contexts, completed to the groups they measure.

Part I partitions the parent support ``B_0 = union_i supp(C_i)`` into fully
commuting (FC) contexts with a deterministic first-fit routine, so every Pauli of
``B_0`` sits in exactly one context.  Coefficient splitting needs overlap, and the
overlap is supplied by the measurement itself: the circuit that measures a
context reads out a *maximal* abelian group of ``2**n`` Paulis
(:mod:`clifford`), and any Pauli of ``B_0`` in that group is estimated by the same
shots.  A Pauli's *multiplicity* is the number of contexts whose measured group
contains it; its coefficient can be split exactly when the multiplicity is at
least two.

Which maximal group a context measures depends on how its generators are
completed.  Three completions are provided:

``canonical``
    single-qubit ``Z``, ``X``, ``Y`` first, then any symplectic-complement vector
    -- the choice a generic synthesis routine would make, blind to the problem;
``mass``
    Paulis of the library in decreasing order of total gradient-coefficient mass
    ``sum_i |A_il|``, so that the heaviest terms become splittable first;
``random``
    Paulis of the library in a seeded random order, to show how much the
    completion choice matters.

A fourth, ``span``, is diagnostic only: the group generated by the parent members
alone, with no completion, which is what overlap would be if only the Pauli
strings the context was built from were measured.  It is not a physical circuit.
"""
from __future__ import annotations

from dataclasses import dataclass, field

import numpy as np

from clifford import (
    MeasurementCircuit,
    complete_generators,
    independent_subset,
    synthesise_measurement_circuit,
)
from symplectic import (
    GF2Basis,
    commutes_with_all,
    masks_from_xz,
    pack,
    unpack,
    xz_from_labels,
)

STRATEGIES = ("canonical", "mass", "random")


@dataclass
class Context:
    """One measurement context and the part of the library its shots estimate."""

    index: int
    home_members: np.ndarray  # library indices of the Part I parent group
    generators: np.ndarray  # packed int64, n independent commuting generators
    parent_rank: int  # rank of the parent group's own span
    completed_from_library: int  # generators added from the preferred list
    circuit: MeasurementCircuit
    members: np.ndarray  # sorted library indices in the measured group
    member_zmask: np.ndarray  # image U P U^dagger = sign * Z**zmask
    member_sign: np.ndarray

    def positions(self, library_indices: np.ndarray) -> np.ndarray:
        """Positions of the given library Paulis within :attr:`members`."""
        library_indices = np.asarray(library_indices, dtype=np.int64)
        positions = np.searchsorted(self.members, library_indices)
        if (positions >= self.members.size).any() or (
            self.members[np.minimum(positions, self.members.size - 1)] != library_indices
        ).any():
            raise KeyError(f"Pauli not measured by context {self.index}")
        return positions


@dataclass
class ContextLibrary:
    """All contexts of one problem, with the library they are indexed against."""

    n_qubits: int
    labels: list[str]
    n_required: int
    xmask: np.ndarray
    zmask: np.ndarray
    home: np.ndarray  # parent context of every required Pauli, -1 for auxiliaries
    contexts: list[Context]
    strategy: str
    seed: int = 0
    _contexts_of: list[np.ndarray] | None = field(default=None, repr=False)

    @property
    def n_contexts(self) -> int:
        return len(self.contexts)

    @property
    def n_library(self) -> int:
        return len(self.labels)

    def multiplicity(self) -> np.ndarray:
        """Number of contexts whose measured group contains each library Pauli."""
        counts = np.zeros(self.n_library, dtype=np.int64)
        for context in self.contexts:
            counts[context.members] += 1
        return counts

    def contexts_of(self) -> list[np.ndarray]:
        """For every library Pauli, the sorted contexts that measure it."""
        if self._contexts_of is None:
            owners: list[list[int]] = [[] for _ in range(self.n_library)]
            for context in self.contexts:
                for member in context.members:
                    owners[member].append(context.index)
            self._contexts_of = [np.asarray(o, dtype=np.int64) for o in owners]
        return self._contexts_of

    def two_qubit_counts(self) -> np.ndarray:
        return np.array([c.circuit.two_qubit_count for c in self.contexts])


def library_labels(problem, auxiliary_labels=()) -> tuple[list[str], int]:
    """Required Paulis in Part I's order, then auxiliaries not already present."""
    labels = list(problem.universal_support)
    present = set(labels)
    extra = [label for label in dict.fromkeys(auxiliary_labels) if label not in present]
    return labels + extra, len(labels)


def coefficient_mass(problem, n_library: int) -> np.ndarray:
    """``sum_i |A_il|`` for every library Pauli (zero for auxiliaries)."""
    from part1_bridge import gradient_matrix

    matrix = gradient_matrix(problem, n_library)
    return np.asarray(abs(matrix).sum(axis=0)).ravel()


def qwc_groups(labels, *, weights: dict[str, float] | None = None) -> list[list[str]]:
    """Qubit-wise commuting groups by first-fit insertion.

    Paulis are inserted in decreasing ``weights`` (default: decreasing Pauli weight),
    ties lexicographic; a Pauli joins the first group on whose every qubit it acts
    as ``I`` or as the group's letter.  The group's letters then define a product
    measurement basis (single-qubit rotations only, no entangling gates), which is
    what the shot-reuse method of Ikhtiarudin et al. measures in.
    """
    labels = list(dict.fromkeys(labels))
    if not labels:
        return []
    n = len(labels[0])
    code = {"I": 0, "X": 1, "Y": 2, "Z": 3}
    if weights is None:
        order = sorted(labels, key=lambda p: (-(n - p.count("I")), p))
    else:
        order = sorted(labels, key=lambda p: (-abs(weights[p]), p))
    letters = np.zeros((0, n), dtype=np.int8)
    members: list[list[str]] = []
    for label in order:
        row = np.fromiter((code[c] for c in label), dtype=np.int8, count=n)
        if members:
            clash = ((row != 0) & (letters != 0) & (letters != row)).any(axis=1)
            fits = np.flatnonzero(~clash)
        else:
            fits = np.zeros(0, dtype=np.int64)
        if fits.size == 0:
            letters = np.vstack([letters, row[None, :]])
            members.append([label])
        else:
            g = int(fits[0])
            letters[g] = np.where(letters[g] == 0, row, letters[g])
            members[g].append(label)
    return members


def build_context_library(
    problem,
    strategy: str = "canonical",
    *,
    seed: int = 0,
    auxiliary_labels=(),
    groups=None,
    extra_groups=(),
) -> ContextLibrary:
    """Complete every parent context and index the library against it.

    ``groups`` replaces Part I's fully commuting parent grouping (e.g. QWC groups of
    the shot-reuse baseline).  ``extra_groups`` are appended as further contexts with
    no home Pauli: they carry data that is already held (the energy measurement of the
    last VQE evaluation), and Paulis they measure that the library does not require
    become auxiliaries.
    """
    if strategy not in STRATEGIES:
        raise ValueError(f"strategy must be one of {STRATEGIES}")
    extra_groups = [list(g) for g in extra_groups]
    auxiliary_labels = list(auxiliary_labels) + [p for g in extra_groups for p in g]
    labels, n_required = library_labels(problem, auxiliary_labels)
    n = problem.n_qubits
    x, z = xz_from_labels(labels)
    xmask, zmask = masks_from_xz(x, z)
    packed = pack(xmask, zmask, n)
    index = {label: position for position, label in enumerate(labels)}

    groups = [list(g) for g in (problem.parent_fc_groups() if groups is None else groups)]
    home = np.full(len(labels), -1, dtype=np.int64)
    for alpha, group in enumerate(groups):
        home[[index[p] for p in group]] = alpha
    groups = groups + extra_groups

    preference = None
    if strategy == "mass":
        mass = coefficient_mass(problem, len(labels))
        order = np.lexsort((np.arange(len(labels)), -mass))
        preference = packed[order]
    elif strategy == "random":
        preference = packed[np.random.default_rng(seed).permutation(len(labels))]

    contexts = []
    for alpha, group in enumerate(groups):
        home_members = np.sort(np.array([index[p] for p in group], dtype=np.int64))
        vectors = packed[home_members]
        generators = [int(vectors[p]) for p in independent_subset(vectors)]
        parent_rank = len(generators)
        generators, from_library = complete_generators(generators, n, preference)
        circuit = synthesise_measurement_circuit(generators, n)
        gx, gz = unpack(np.array(generators, dtype=np.int64), n)
        members = np.flatnonzero(commutes_with_all(xmask, zmask, gx, gz))
        if not np.isin(home_members, members).all():  # pragma: no cover
            raise AssertionError(f"context {alpha} does not measure its own members")
        member_zmask, member_sign = circuit.diagonal_images(x[members], z[members])
        contexts.append(
            Context(
                index=alpha,
                home_members=home_members,
                generators=np.array(generators, dtype=np.int64),
                parent_rank=parent_rank,
                completed_from_library=from_library,
                circuit=circuit,
                members=members,
                member_zmask=member_zmask,
                member_sign=member_sign,
            )
        )
    return ContextLibrary(
        n_qubits=n,
        labels=labels,
        n_required=n_required,
        xmask=xmask,
        zmask=zmask,
        home=home,
        contexts=contexts,
        strategy=strategy,
        seed=seed,
    )


def span_multiplicity(problem) -> np.ndarray:
    """Multiplicity of every required Pauli under the diagnostic ``span`` rule."""
    labels = list(problem.universal_support)
    n = problem.n_qubits
    xmask, zmask = masks_from_xz(*xz_from_labels(labels))
    packed = pack(xmask, zmask, n)
    index = {label: position for position, label in enumerate(labels)}
    counts = np.zeros(len(labels), dtype=np.int64)
    for group in problem.parent_fc_groups():
        basis = GF2Basis()
        for p in group:
            basis.add(int(packed[index[p]]))
        counts += basis.reduce_many(packed) == 0
    return counts
